using src.config;
using src.libraries;
using src.modules;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace src.utils
{
    /// <summary>
    /// This class generates the premake system file with the modules and libraries diretories.
    /// </summary>
    internal class PremakeSystemWriter
    {
        static IList<string> content = new List<string>();
        public static void Write(Config config, PremakeLibrary[] libraries, PremakeModule[] modules)
        {
            File.Delete("premake-system.lua");
            AddDisclaimer();
            AddPath(config.ModulesPath,"modules");
            AddPath(config.LibrariesPath,"libraries");
            AddLibs(libraries);
            AddModules(modules);
            AddIncludeDirsSetFunction();
            AddIncludeDirs();
            File.WriteAllText("premake-system.lua", string.Join("\n", content));
        }
        static void AddDisclaimer()
        {
            content.Add("---WARNING this file was generated by premake-manager-cli!!!\n---change at your own risk!");
        }
        static void AddPath(string? path, string defaultPath)
        {
            content.Add($"premake.path = premake.path..\";\"..path.join(_MAIN_SCRIPT_DIR, \"{(string.IsNullOrEmpty(path) ? defaultPath : path)}\")");
        }
        static void AddLibs(PremakeLibrary[] libraries)
        {
            AddLibsStart();
            foreach (var lib in libraries)
            {
                AddLib(lib);
            }
            content.Add("    list = function() local c=0 for _,d in pairs(Libraries) do if type(d)=='table' then c=c+1 end end print('--- Libraries ('..c..') ---') for n,d in pairs(Libraries) do if type(d)=='table' then print(n..' version: '..d.version) end end print('----------------------- \\n') end,"); AddLibsEnd();
        }
        static void AddModules(PremakeModule[] modules)
        {
            AddModulesStart();
            foreach (var module in modules)
            {
                AddModule(module);
            }
            content.Add("    list = function() local c=0 for _,d in pairs(Modules) do if type(d)=='table' then c=c+1 end end print('--- Modules ('..c..') ---') for n,d in pairs(Modules) do if type(d)=='table' then print(n..' version: '..d.version) end end print('-----------------------\\n') end,"); AddModulesEnd();
        }
        static void AddLibsStart()
        {
            content.Add($"\n---LIBRARIES---\n_G.Libraries =\n{{");
        }
        static void AddLib(PremakeLibrary lib)
        {
            content.Add($"    [\"{lib.library.Split('/')[1]}\"] = {{ version = \"{lib.version}\" }},");
        }
        static void AddLibsEnd()
        {
            content.Add($"}}");
        }
        static void AddModulesStart()
        {
            content.Add($"\n---MODULES---\n_G.Modules =\n{{");
        }
        static void AddModule(PremakeModule mod)
        {
            content.Add($"    [\"{mod.module}\"] = {{ version = \"{mod.version}\" }},");
        }
        static void AddModulesEnd()
        {
            content.Add($"}}");
        }
        static void AddIncludeDirsSetFunction()
        {
            content.Add(@"
---INCLUDE_DIRS---
local function setincludedirs(name, path)
    IncludeDirs = IncludeDirs or {}
    local cleanName = string.gsub(name, ""-"", ""_"")
    IncludeDirs[cleanName] = _SCRIPT_DIR .. ""/"" .. path
end
");

            content.Add("_G.setincludedirs = setincludedirs");
        }
        static void AddIncludeDirs()
        {
            content.Add("_G.IncludeDirs = {}");
        }
    }
}
