using src.config;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace src.utils
{
    /// <summary>
    /// This class generates the premake system file with the modules and libraries diretories.
    /// </summary>
    internal class PremakeSystemWriter
    {
        static IList<string> content = new List<string>();
        public static void Write(Config config)
        {
            AddDisclaimer();
            AddPath(config.ModulesPath,"modules");
            AddPath(config.LibrariesPath,"libraries");
            if (config.Modules != null)
            {
                foreach (var item in config.Modules)
                {
                    AddModule(item.Value.entryPoint ?? item.Key);
                }
                try
                {
                    File.Delete("premake-system.lua");
                }
                catch (Exception)
                {

                }
            }
            File.WriteAllText("premake-system.lua", string.Join("\n", content));
        }
        static void AddDisclaimer()
        {
            content.Add("---WARNING this file was generated by premake-manager-cli!!!\n---change at your own risk!");
        }
        static void AddPath(string? path, string defaultPath)
        {
            content.Add($"premake.path = premake.path..\";\"..path.join(_MAIN_SCRIPT_DIR, \"{(string.IsNullOrEmpty(path) ? defaultPath : path)}\")");
        }
        static void AddModule(string entryPoint)
        {
            content.Add($"require \"{entryPoint}\"");
        }
    }
}
