name: Build and Test per Platform
permissions:
  contents: write
on:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    env:
      DOTNET_PUBLISH_COMMON: >
        -c Release
        -p:PublishSingleFile=true
        --self-contained true
        -p:IncludeNativeLibrariesForSelfExtract=true
        -p:PublishTrimmed=true
        -p:PublishReadyToRun=false
        -p:DebugType=None
        -p:DebugSymbols=false
        -p:TrimMode=partial
        -p:InvariantGlobalization=true
        -p:EnableCompressionInSingleFile=true
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
        cache: true
        cache-dependency-path: ${{ github.workspace }}/premake-manager-cli
    - name: Installing premake5
      uses: Jarod42/install-premake5@v7
      ver
    - name: run premake5
      run: premake5 vs2026
    - name: Install dependencies
      run: dotnet restore ${{ github.workspace }}

    - name: Publish
      shell: bash
      run: |
        PUBLISH_DIR="${{ github.workspace }}/publish-artifacts"

        if [ "${{ runner.os }}" == "Windows" ]; then
            dotnet publish "${{ github.workspace }}" -r win-x64 $DOTNET_PUBLISH_COMMON -o "$PUBLISH_DIR" 
        elif [ "${{ runner.os }}" == "Linux" ]; then
            dotnet publish ${{ github.workspace }} -r linux-x64 $DOTNET_PUBLISH_COMMON -o "$PUBLISH_DIR"
        elif [ "${{ runner.os }}" == "macOS" ]; then
            dotnet publish ${{ github.workspace }} -r osx-arm64 -p:PlatformTarget=arm64 $DOTNET_PUBLISH_COMMON -o "$PUBLISH_DIR"
        fi
    - name: Run Self-Tests
      shell: bash
      run: |
        EXE_PATH="${{ github.workspace }}/publish-artifacts/premake-manager-cli"
        
        if [ "${{ runner.os }}" == "Windows" ]; then
            "$EXE_PATH.exe" test all
        else
            chmod +x "$EXE_PATH"
            "$EXE_PATH" test all
        fi
    - name: Upload Artifacts
      uses: actions/upload-artifact@v6
      with:
        # Use the matrix OS to create unique names like: build-windows-latest
        name: build-${{ matrix.os }}
        # Point to the same directory used in the Publish step
        path: ${{ github.workspace }}/publish-artifacts/
        # Optional: How long to keep the artifact (default 90 days)
        retention-days: 10

upload-to-release:
    if: github.event_name == 'release'
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v6
        with:
          path: all-artifacts # This downloads build-windows-latest, build-ubuntu-latest, etc.

      - name: Prepare Assets for Release
        run: |
          mkdir assets
          # Loop through the downloaded folders and rename files for clarity
          # Windows
          cp all-artifacts/build-windows-latest/premake-manager-cli.exe assets/premake-manager-cli-win.exe
          # Linux
          cp all-artifacts/build-ubuntu-latest/premake-manager-cli assets/premake-manager-cli-linux
          # macOS
          cp all-artifacts/build-macos-latest/premake-manager-cli assets/premake-manager-cli-darwin

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
